export const REGIONS = [
  { id: 'TATARSTAN', name: 'Республика Татарстан' },
  { id: 'SARATOV', name: 'Саратовская область' },
]

export const MUNICIPALITIES = {
  TATARSTAN: [
    { id: 'KAZAN', name: 'г. Казань' },
    { id: 'NAB_CHELNY', name: 'г. Набережные Челны' },
    { id: 'NIZHNEKAMSK', name: 'г. Нижнекамск' },
    { id: 'ALMET', name: 'г. Альметьевск' },
  ],
  SARATOV: [
    { id: 'SARATOV_CITY', name: 'г. Саратов' },
    { id: 'ENGELS', name: 'г. Энгельс' },
    { id: 'BALAKOVO', name: 'г. Балаково' },
  ],
}

export const DICT = {
  FAMILY_RELATION: [
    { code: 'WIFE', label: 'Супруга / супруг военнослужащего', hint: 'Включая семейные меры поддержки и выплаты.' },
    { code: 'SELF', label: 'Сам военнослужащий / участник СВО', hint: 'Подберём меры, относящиеся непосредственно к вам.' },
    { code: 'MOTHER', label: 'Мать военнослужащего', hint: 'Родитель военнослужащего.' },
    { code: 'FATHER', label: 'Отец военнослужащего', hint: 'Родитель военнослужащего.' },
    { code: 'CHILD', label: 'Ребёнок военнослужащего', hint: 'Для несовершеннолетних и молодых взрослых — при выполнении условий конкретной меры.' },
  ],
  MILITARY_STATUS: [
    { code: 'MOBILIZED', label: 'Мобилизован' },
    { code: 'CONTRACT_SVO', label: 'Служит по контракту, участник СВО' },
    { code: 'CONSCRIPT', label: 'Проходит срочную службу' },
    { code: 'SVO_PARTICIPANT', label: 'Участник СВО' },
    { code: 'VETERAN_BD', label: 'Ветеран боевых действий' },
    { code: 'DECEASED_MILITARY', label: 'Погиб' },
    { code: 'VOLUNTEER_SVO', label: 'Доброволец СВО' },
  ],
  DISABILITY_GROUP: [
    { code: 'I', label: 'I группа' },
    { code: 'II', label: 'II группа' },
    { code: 'III', label: 'III группа' },
  ],
  EDUCATION_LEVEL: [
    { code: 'PRESCHOOL', label: 'Детский сад' },
    { code: 'SCHOOL', label: 'Школа' },
    { code: 'COLLEGE', label: 'Колледж / СПО' },
    { code: 'UNIVERSITY', label: 'Вуз' },
  ],
  INCOME_RANGE: [
    { code: 'UNDER_27', label: 'До 27 000 ₽', hint: 'ниже 27 тыс. ₽ в месяц на семью' },
    { code: '27_40', label: '27 000–40 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: '40_60', label: '40 000–60 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: '60_100', label: '60 000–100 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: '100_150', label: '100 000–150 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: '150_200', label: '150 000–200 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: 'OVER_200', label: 'Более 200 000 ₽', hint: 'примерный совокупный доход семьи' },
    { code: 'UNKNOWN', label: 'Не хочу указывать', hint: 'В подборе доход не будет использоваться.' },
  ],
  EMPLOYMENT_STATUS: [
    { code: 'EMPLOYED', label: 'Работаю' },
    { code: 'UNEMPLOYED', label: 'Не работаю' },
    { code: 'SELF', label: 'Самозанятый / ИП' },
    { code: 'STUDENT', label: 'Учусь' },
    { code: 'PENSIONER', label: 'Пенсионер' },
    { code: 'UNKNOWN', label: 'Не хочу указывать' },
  ],
  LEGAL_ISSUE_CATEGORY: [
    { id: 'b51a01a1-07e6-4bc1-8a7c-fb3463d1732e', code: 'HOUSING', label: 'Жилищный вопрос' },
    { id: '6a19582e-dcbe-4bb4-a13e-272bf8bf41bb', code: 'FAMILY', label: 'Семейный вопрос' },
    { id: '675fb65c-b3dd-4ccc-aa8a-022b2c5477bf', code: 'LABOR', label: 'Трудовой вопрос' },
    { id: '60fdb984-645c-4d5f-a87d-4d33e9459609', code: 'SOCIAL_SUPPORT', label: 'Социальная поддержка' },
    { id: '9b006ae3-e67c-4aa8-87bb-cce4a2b22a39', code: 'OTHER', label: 'Другое' },
  ],
}
export const LABELS = {
  supportType: {
    PAYMENT: 'Выплата',
    COMPENSATION: 'Компенсация',
    BENEFIT: 'Льгота',
    SERVICE: 'Услуга',
    HOUSING_PROGRAM: 'Жилищная программа',
    LEGAL_AID: 'Бесплатная юридическая помощь',
    PENSION: 'Пенсия',
    EDUCATION_RIGHT: 'Право на образование и развитие',
    ADMISSION_PRIORITY: 'Преимущественное право при зачислении',
    FOOD_SUPPORT: 'Питание',
    TRAVEL_BENEFIT: 'Пособие на поездки',
    CULTURE_BENEFIT: 'Пособие в культурно-досуговой сфере',
    INSURANCE_PAYMENT: 'Страховая выплата',
    EMPLOYMENT_SUPPORT: 'Поддержка в сфере трудоустройства',
    SOCIAL_SERVICE: 'Социальная услуга',
    CHILDCARE_BENEFIT: 'Пособие по уходу за ребёнком',
  },
  level: { FEDERAL: 'Федеральная', REGIONAL: 'Региональная', MUNICIPAL: 'Муниципальная' },
  recipient: { USER: 'Вам', SPOUSE: 'Военнослужащему', CHILD: 'Ребёнку', FAMILY: 'Семье' },
  frequency: { ONE_TIME: 'единовременно', MONTHLY: 'в месяц', YEARLY: 'в год' },
  channel: {
    GOSUSLUGI: 'Госуслуги',
    SFR: 'Социальный фонд России',
    SOCIAL_PROTECTION: 'Орган социальной защиты',
    MFC: 'МФЦ',
    SCHOOL: 'Школа / детский сад',
    EDUCATIONAL_ORGANIZATION: 'Образовательная организация',
    FNS: 'ФНС России',
    BANK: 'Банк',
    EMPLOYMENT_SERVICE: 'Служба занятости',
    EMPLOYMENT_CENTER: 'Центр занятости',
    CULTURE_INSTITUTION: 'Учреждение культуры',
    SOCIAL_SERVICE_ORGANIZATION: 'Организация социального обслуживания',
    CREDITOR: 'Кредитор / банк / МФО',
    HOUSING_AUTHORITY: 'Уполномоченный жилищный орган',
    EMPLOYER: 'Работодатель',
  },
  status: { NOT_APPLIED: 'Не подавали', SUBMITTED: 'Подано', APPROVED: 'Назначено', RECEIVED: 'Получено' },
  statusShort: { NOT_APPLIED: 'Не под.', SUBMITTED: 'Подано', APPROVED: 'Назнач.', RECEIVED: 'Получено' },
}

const FZ = (name, url) => ({ name, url })

export const CATALOG = [
  {
    id: 'injury-once',
    name: 'Единовременная выплата при ранении или контузии',
    description: 'Страховая единовременная выплата военнослужащему при ранении (контузии), полученном при выполнении задач в ходе СВО.',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'SPOUSE',
    amount: 3000000, frequency: 'ONE_TIME',
    applicationRequired: true, channel: 'GOSUSLUGI', actionUrl: 'https://www.gosuslugi.ru',
    documents: ['Паспорт', 'Военный билет', 'Справка о характере травмы из воинской части или госпиталя', 'Реквизиты банковского счёта'],
    validTo: null, urgency: 'high',
    npa: [FZ('ФЗ № 306-ФЗ «О денежном довольствии военнослужащих»', 'https://www.consultant.ru/document/cons_doc_LAW_121895/')],
    rules: [{
      items: [
        { param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO', label: 'военнослужащий мобилизован или служит по контракту' },
        { param: 'injury', op: 'TRUE', label: 'есть ранение или контузия' },
      ],
    }],
  },
  {
    id: 'disability-edv',
    name: 'Ежемесячная выплата по инвалидности вследствие военной травмы',
    description: 'Ежемесячная денежная компенсация; размер зависит от группы инвалидности, установленной из-за военной травмы.',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'SPOUSE',
    amount: 20000, frequency: 'MONTHLY',
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Паспорт', 'Справка МСЭ об инвалидности', 'Заключение о причинной связи травмы'],
    validTo: null,
    npa: [FZ('ФЗ № 306-ФЗ «О денежном довольствии военнослужащих»', 'https://www.consultant.ru/document/cons_doc_LAW_121895/')],
    rules: [
      { amountOverride: 30000, items: [
        { param: 'disability', op: 'TRUE', label: 'установлена инвалидность' },
        { param: 'disabilityGroup', op: 'EQUALS', value: 'I', label: 'I группа инвалидности' },
      ]},
      { amountOverride: 20000, items: [
        { param: 'disability', op: 'TRUE', label: 'установлена инвалидность' },
        { param: 'disabilityGroup', op: 'IN', value: 'II,III', label: 'II или III группа инвалидности' },
      ]},
    ],
  },
  {
    id: 'credit-holiday',
    name: 'Кредитные каникулы по действующим кредитам',
    description: 'Право приостановить платежи по кредитам и займам на период участия в СВО.',
    supportType: 'SERVICE', level: 'FEDERAL', recipient: 'FAMILY',
    amount: null, frequency: null,
    applicationRequired: true, channel: 'BANK', actionUrl: null,
    documents: ['Заявление в банк', 'Документ, подтверждающий участие в СВО'],
    validTo: null,
    npa: [FZ('ФЗ № 377-ФЗ (кредитные каникулы для участников СВО)', 'https://www.consultant.ru/')],
    rules: [{ items: [{ param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO', label: 'военнослужащий участвует в СВО' }] }],
  },
  {
    id: 'child-allowance',
    name: 'Ежемесячное пособие на ребёнка военнослужащего',
    description: 'Выплата на каждого ребёнка военнослужащего, участвующего в СВО, на период службы.',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'CHILD',
    amount: 15000, frequency: 'MONTHLY',
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Свидетельство о рождении ребёнка', 'Справка из воинской части', 'Паспорт заявителя'],
    validTo: null,
    npa: [FZ('ФЗ № 306-ФЗ, ст. 12.1', 'https://www.consultant.ru/document/cons_doc_LAW_121895/')],
    rules: [{ items: [
      { param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO', label: 'военнослужащий участвует в СВО' },
      { param: 'child', op: 'EXISTS', label: 'в семье есть дети' },
    ]}],
  },
  {
    id: 'tax-benefit',
    name: 'Налоговые льготы для семей участников СВО',
    description: 'Освобождение от налога на имущество, льготы по транспортному налогу и НДФЛ.',
    supportType: 'BENEFIT', level: 'FEDERAL', recipient: 'FAMILY',
    amount: null, frequency: 'YEARLY',
    applicationRequired: true, channel: 'FNS', actionUrl: 'https://www.nalog.gov.ru',
    documents: ['Заявление в личном кабинете ФНС', 'Документ, подтверждающий статус'],
    validTo: null,
    npa: [FZ('Налоговый кодекс РФ, гл. 32', 'https://www.consultant.ru/document/cons_doc_LAW_19671/')],
    rules: [{ items: [{ param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO,SVO_PARTICIPANT,VOLUNTEER_SVO,VETERAN_BD', label: 'участник СВО в семье' }] }],
  },
  {
    id: 'deceased-once',
    name: 'Единовременная выплата членам семьи погибшего военнослужащего',
    description: 'Единовременная выплата близким родственникам в случае гибели военнослужащего при выполнении задач в ходе СВО.',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'FAMILY',
    amount: 12000000, frequency: 'ONE_TIME',
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Паспорт', 'Свидетельство о смерти', 'Документы, подтверждающие родство', 'Справка о причинной связи'],
    validTo: null, urgency: 'high',
    npa: [FZ('ФЗ № 306-ФЗ', 'https://www.consultant.ru/document/cons_doc_LAW_121895/')],
    rules: [{ items: [{ param: 'militaryStatus', op: 'EQUALS', value: 'DECEASED_MILITARY', label: 'военнослужащий погиб' }] }],
  },
  {
    id: 'survivor-pension',
    name: 'Пенсия по случаю потери кормильца для детей',
    description: 'Ежемесячная пенсия детям погибшего военнослужащего до 18 лет (или до 23 лет при очном обучении).',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'CHILD',
    amount: 16000, frequency: 'MONTHLY',
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Свидетельство о рождении', 'Свидетельство о смерти', 'Справка об обучении (с 18 лет)'],
    validTo: null,
    npa: [FZ('ФЗ № 4468-1 «О пенсионном обеспечении военнослужащих»', 'https://www.consultant.ru/')],
    rules: [{ items: [
      { param: 'militaryStatus', op: 'EQUALS', value: 'DECEASED_MILITARY', label: 'военнослужащий погиб' },
      { param: 'child', op: 'EXISTS', label: 'в семье есть дети' },
    ]}],
  },
  {
    id: 'rt-mob-once',
    name: 'Региональная выплата при мобилизации (Республика Татарстан)',
    description: 'Единовременная региональная выплата семье мобилизованного жителя Татарстана (демо-данные).',
    supportType: 'PAYMENT', level: 'REGIONAL', recipient: 'SPOUSE',
    amount: 100000, frequency: 'ONE_TIME',
    applicationRequired: true, channel: 'MFC', actionUrl: null,
    documents: ['Паспорт', 'Документ о мобилизации', 'Реквизиты счёта'],
    validTo: null, urgency: 'high',
    npa: [FZ('Постановление КМ РТ (демо)', 'https://tatarstan.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'TATARSTAN', label: 'проживание в Республике Татарстан' },
      { param: 'militaryStatus', op: 'EQUALS', value: 'MOBILIZED', label: 'военнослужащий мобилизован' },
    ]}],
  },
  {
    id: 'sar-mob-once',
    name: 'Региональная выплата семьям участников СВО (Саратовская область)',
    description: 'Единовременная региональная выплата семьям мобилизованных жителей Саратовской области (демо-данные).',
    supportType: 'PAYMENT', level: 'REGIONAL', recipient: 'SPOUSE',
    amount: 50000, frequency: 'ONE_TIME',
    applicationRequired: true, channel: 'MFC', actionUrl: null,
    documents: ['Паспорт', 'Справка о мобилизации', 'Реквизиты счёта'],
    validTo: null,
    npa: [FZ('Постановление Правительства Саратовской области (демо)', 'https://saratov.gov.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'SARATOV', label: 'проживание в Саратовской области' },
      { param: 'militaryStatus', op: 'EQUALS', value: 'MOBILIZED', label: 'военнослужащий мобилизован' },
    ]}],
  },
  {
    id: 'rt-school-meal',
    name: 'Бесплатное двухразовое питание для школьника',
    description: 'Бесплатные завтрак и обед для детей из семей участников СВО в школах Республики Татарстан.',
    supportType: 'SERVICE', level: 'REGIONAL', recipient: 'CHILD',
    amount: null, frequency: null,
    applicationRequired: true, channel: 'SCHOOL', actionUrl: null,
    documents: ['Заявление в школу', 'Справка об участии родителя в СВО'],
    validTo: null,
    npa: [FZ('НПА-1122: меры социальной поддержки в РТ (демо)', 'https://tatarstan.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'TATARSTAN', label: 'Республика Татарстан' },
      { param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO,SVO_PARTICIPANT,VOLUNTEER_SVO,VETERAN_BD', label: 'родитель — участник СВО' },
      { param: 'child_education', op: 'EQUALS', value: 'SCHOOL', label: 'ребёнок учится в школе' },
      { param: 'child_grade', op: 'BETWEEN', valueFrom: 1, valueTo: 11, label: '1–11 класс' },
    ]}],
  },
  {
    id: 'sar-school-meal',
    name: 'Бесплатное питание для школьника (Саратовская область)',
    description: 'Бесплатное питание детей из семей участников СВО в школах Саратовской области (демо-данные).',
    supportType: 'SERVICE', level: 'REGIONAL', recipient: 'CHILD',
    amount: null, frequency: null,
    applicationRequired: true, channel: 'SCHOOL', actionUrl: null,
    documents: ['Заявление в школу', 'Справка об участии родителя в СВО'],
    validTo: null,
    npa: [FZ('Региональный НПА (демо)', 'https://saratov.gov.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'SARATOV', label: 'Саратовская область' },
      { param: 'militaryStatus', op: 'IN', value: 'MOBILIZED,CONTRACT_SVO,SVO_PARTICIPANT,VOLUNTEER_SVO,VETERAN_BD', label: 'родитель — участник СВО' },
      { param: 'child_education', op: 'EQUALS', value: 'SCHOOL', label: 'ребёнок учится в школе' },
      { param: 'child_grade', op: 'BETWEEN', valueFrom: 1, valueTo: 11, label: '1–11 класс' },
    ]}],
  },
  {
    id: 'camp-voucher',
    name: 'Путёвка в загородный лагерь для ребёнка',
    description: 'Бесплатная или субсидированная путёвка в загородный лагерь для детей участников СВО (демо-данные).',
    supportType: 'SERVICE', level: 'REGIONAL', recipient: 'CHILD',
    amount: null, frequency: 'YEARLY',
    applicationRequired: true, channel: 'MFC', actionUrl: null,
    documents: ['Свидетельство о рождении', 'Паспорт заявителя', 'Справка об участии в СВО'],
    validTo: null,
    npa: [FZ('Региональная программа детского отдыха (демо)', 'https://tatarstan.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'TATARSTAN', label: 'Республика Татарстан' },
      { param: 'child_age', op: 'BETWEEN', valueFrom: 7, valueTo: 15, label: 'ребёнок 7–15 лет' },
    ]}],
  },
  {
    id: 'gas-comp',
    name: 'Компенсация за газификацию дома',
    description: 'Компенсация расходов на подключение газа для семей участников СВО (демо-данные).',
    supportType: 'COMPENSATION', level: 'REGIONAL', recipient: 'FAMILY',
    amount: 100000, frequency: 'ONE_TIME',
    applicationRequired: true, channel: 'MFC', actionUrl: null,
    documents: ['Договор о подключении газа', 'Платёжные документы', 'Паспорт', 'Справка об участии в СВО'],
    validTo: null,
    npa: [FZ('Региональная программа газификации (демо)', 'https://tatarstan.ru')],
    rules: [{ items: [
      { param: 'region', op: 'EQUALS', value: 'TATARSTAN', label: 'Республика Татарстан' },
      { param: 'gasification', op: 'TRUE', label: 'требуется газификация' },
    ]}],
  },
  {
    id: 'legal-aid',
    name: 'Бесплатная юридическая помощь',
    description: 'Консультации юриста по вопросам мер поддержки, льгот и документов для семей участников СВО.',
    supportType: 'SERVICE', level: 'REGIONAL', recipient: 'FAMILY',
    amount: null, frequency: null,
    applicationRequired: false, channel: 'MFC', actionUrl: null,
    documents: ['Паспорт'],
    validTo: null,
    npa: [],
    rules: [{ items: [{ param: 'region', op: 'IN', value: 'TATARSTAN,SARATOV', label: 'действует в вашем регионе' }] }],
  },
  {
    id: 'low-income-child',
    name: 'Единое пособие на детей (для семей с невысоким доходом)',
    description: 'Ежемесячное единое пособие в связи с рождением и воспитанием ребёнка. Размер зависит от дохода и имущественной обеспеченности семьи.',
    supportType: 'PAYMENT', level: 'FEDERAL', recipient: 'CHILD',
    amount: 12000, frequency: 'MONTHLY',
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Паспорт', 'Свидетельства о рождении детей', 'Данные о доходах семьи'],
    validTo: null,
    npa: [FZ('ФЗ № 81-ФЗ «О государственных пособиях гражданам, имеющим детей»', 'https://www.consultant.ru/')],
    rules: [{ items: [
      { param: 'incomeCategory', op: 'EQUALS', value: 'LOW', label: 'доход ниже прожиточного минимума' },
      { param: 'child', op: 'EXISTS', label: 'в семье есть дети' },
    ]}],
  },
  {
    id: 'housing-subsidy',
    name: 'Субсидия на оплату ЖКУ',
    description: 'Компенсация части расходов на ЖКУ, если платежи превышают допустимую долю дохода семьи.',
    supportType: 'COMPENSATION', level: 'REGIONAL', recipient: 'FAMILY',
    amount: null, frequency: 'MONTHLY',
    applicationRequired: true, channel: 'MFC', actionUrl: null,
    documents: ['Паспорт', 'Справки о доходах всех членов семьи', 'Квитанции ЖКУ', 'Документ о собственности/найме жилья'],
    validTo: null,
    npa: [FZ('ЖК РФ, ст. 159', 'https://www.consultant.ru/document/cons_doc_LAW_8386/')],
    rules: [{ items: [
      { param: 'housingProblem', op: 'TRUE', label: 'расходы на ЖКУ существенны' },
      { param: 'incomeCategory', op: 'EQUALS', value: 'LOW', label: 'доход ниже прожиточного минимума' },
    ]}],
  },
  {
    id: 'psych-support',
    name: 'Психологическая поддержка семьи',
    description: 'Бесплатные консультации психолога для семей участников СВО: горячая линия, очные и онлайн-приёмы.',
    supportType: 'SERVICE', level: 'FEDERAL', recipient: 'FAMILY',
    amount: null, frequency: null,
    applicationRequired: false, channel: 'GOSUSLUGI', actionUrl: 'https://www.gosuslugi.ru',
    documents: [],
    validTo: null,
    npa: [],
    rules: [{ items: [{ param: 'familyRelation', op: 'IN', value: 'WIFE,SELF,MOTHER,FATHER', label: 'доступно для семей участников СВО' }] }],
  },
  {
    id: 'child-survivor-support',
    name: 'Меры поддержки ребёнку погибшего военнослужащего',
    description: 'Демо-меры для ребёнка военнослужащего, погибшего при выполнении задач. Условия зависят от возраста и обучения.',
    supportType: 'BENEFIT', level: 'FEDERAL', recipient: 'USER',
    amount: null, frequency: null,
    applicationRequired: true, channel: 'SFR', actionUrl: 'https://sfr.gov.ru/',
    documents: ['Паспорт или свидетельство о рождении', 'Документы о родстве', 'Документы о статусе военнослужащего'],
    validTo: null, urgency: 'high',
    npa: [],
    rules: [
      { items: [
        { param: 'familyRelation', op: 'EQUALS', value: 'CHILD', label: 'вы — ребёнок военнослужащего' },
        { param: 'militaryStatus', op: 'EQUALS', value: 'DECEASED_MILITARY', label: 'военнослужащий погиб' },
        { param: 'orphan', op: 'TRUE', label: 'есть статус сироты / ребёнка, оставшегося без попечения' },
      ] },
      { items: [
        { param: 'familyRelation', op: 'EQUALS', value: 'CHILD', label: 'вы — ребёнок военнослужащего' },
        { param: 'militaryStatus', op: 'EQUALS', value: 'DECEASED_MILITARY', label: 'военнослужащий погиб' },
        { param: 'applicant_age', op: 'BETWEEN', valueFrom: 18, valueTo: 23, label: 'возраст до 23 лет' },
        { param: 'applicant_full_time', op: 'TRUE', label: 'очное обучение' },
      ] },
      { items: [
        { param: 'familyRelation', op: 'EQUALS', value: 'CHILD', label: 'вы — ребёнок военнослужащего' },
        { param: 'militaryStatus', op: 'EQUALS', value: 'DECEASED_MILITARY', label: 'военнослужащий погиб' },
        { param: 'applicant_age', op: 'LTE', valueTo: 17, label: 'возраст до 18 лет' },
      ] },
    ],
  },
]
