spring.application.name=zabota-bot
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/zabota_bot_db}
spring.datasource.username=${DB_USERNAME:yousef}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=${SERVER_PORT:8080}

max.bot.mode=${MAX_BOT_MODE:longpolling}

max.bot.longpolling.token=${MAX_BOT_TOKEN}
max.bot.longpolling.poll-timeout=30
max.bot.longpolling.update-types=MESSAGE_CREATED,BOT_STARTED,MESSAGE_CALLBACK