spring.application.name=zabota-bot

spring.datasource.url=jdbc:postgresql://localhost:5432/zabota_bot_db
spring.datasource.username=yousef
spring.datasource.password=20062006
spring.datasource.driver-class-name=org.postgresql.Driver
